server:
  port: 8762

spring:
  application:
    name: microservice-provider-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
