server:
  port: 8899
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ppj19891020/SpringcloudConfig.git
      label: master
      profile: dev
      name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  user:
    name: admin
    password: 12345678
